- 
  name: 'Deploy a web application'
  hosts: node01
  roles:
    - python_packages
    - mysql_db
    - flask_web


## NOTE: ansible-vault password file is located in /tmp/get_pass.py 

  # - name: monitor webapp
  #   command: /opt/monitor_webapp.py
  #   async: 360
  #   poll: 0
  #   register: webapp_result

  # - name: monitor webapp
  #   command: /opt/monitor_database.py
  #   async: 360
  #   poll: 0
  #   register: database_result

  # - name: Check Status of webapp task
  #   async_status:
  #     jid: "{{ webapp_result.ansible_job_id }}"
  #   register: job_result
  #   until: job_result.finished
  #   retries: 30

  # - name: Check Status of databas task
  #   async_status:
  #     jid: "{{ database_result.ansible_job_id }}"
  #   register: job_result
  #   until: job_result.finished
  #   retries: 30
